### ISSUE TITLE
[BUG] Author of this repository sucks at Nunu Jungle

### ISSUE THREAD

**Issue by iahuang** [theloni-monk/Julia-GL#1]
Running the following code
```batch
$ start "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Riot Games\League of Legends"
```

Causes a massive brain diff when run in the context of user [theloni-monk](https://github.com/theloni-monk). Please report, ff, and go next.

**Comment by iahuang** [comment]
**UPDATE**

This issue was successfully reproduced about a month ago. For more information, see [here](https://www.leagueofgraphs.com/match/na/3841025144#participant5)

**Comment by theloni-monk** [comment]
closed because the author of this issue is hardstuck silver and cant talk.
